// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipodixcctvpkbwkpjaff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwb2RpeGNjdHZwa2J3a3BqYWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0ODY4NzQsImV4cCI6MjA4MjA2Mjg3NH0.fzzswee_RgfFYDaVlBln3ZzcRGSgbTfMF3RocycX5LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});